---
- name: Create virtual machine
  run_once: true
  proxmox_kvm:
    api_user: "{{ proxmox.api_user }}"
    api_password: "{{ proxmox.api_password }}"
    api_host: "{{ proxmox.api_host }}"
    name: "{{ item.value.name }}"
    node: "{{ item.value.node }}"
